#permalink: /:title
#timezone: Chinese/Chong_Qing

#copy from beiyu
#{
auto: true

markdown: rdiscount
pygments: true
#paginate: 8
permalink: /:title

title: wuranbo.me
url: http://wuranbo.me
feed: /atom.xml
author_info: <a href="http://wuranbo.me/">WuRanbo</a>
author:
  name: wuranbo
  email: wuranbo@gmail.com
uservar:
  blog: 博客
  misc: 胡言乱语
  myname-zh: 吴冉波
#}
